# Create auth config file
apiVersion: apiserver.config.k8s.io/v1beta1
kind: AuthenticationConfiguration
jwt:
  - issuer:
      url: https://token.actions.githubusercontent.com
      audiences:
        - kubernetes-test
    claimMappings:
      username:
        claim: sub
        prefix: "github:"